#!/bin/bash

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%C(green)%ar%Creset"
AUTHOR="%C(bold blue)%an%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$REFS $SUBJECT"

function pretty_git_log() {
	git log --graph --pretty="tformat:$FORMAT" $* |
		column -t -s '{' |
		less -FRS
}
